name: Welcome New Collaborator

on:
  repository_dispatch:
    types: [collaborator-added]

jobs:
  welcome-message:
    if: github.event.action == 'collaborator-added'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Welcome new member
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "A new collaborator was added to the repository. Sending welcome message..."
          # Example: Create an issue to welcome the new collaborator
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title":"Welcome to the Team!","body":"We have a new collaborator. Welcome aboard!"}'
